[package]
name = "toolkit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
mem_dbg = "0.3.0"
num = "0.4.3"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
debug = true
